language: java android

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.2.0
    - android-25

jdk:
 - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

script:
 - ./gradlew clean build

os: linux